name: Test Get Email from Github Username
on:
  workflow_dispatch:

  push:
    branches:
      - "main"

jobs:
  get_easy_email:
    runs-on: ubuntu-latest
    name: Get an easy to find email
    steps:
      - name: get easy email
        id: get_easy_email_test
        uses: ndelangen/email-by-username-action@main
        with:
          github-username: "ndelangen"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo the output email
        run: echo "The email is ${{ steps.get_easy_email_test.outputs.email }}"

  fail_no_email:
    runs-on: ubuntu-latest
    name: Fail on user account that has no email or public commits
    steps:
      - name: fail bad email
        id: fail_bad_email_test
        uses: ndelangen/email-by-username-action@main
        continue-on-error: true
        with:
          github-username: "hstought"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Job succeeded (if previous step failed)
        if: ${{ failure() }}
        run: echo "Job succeeded as expected (fail_bad_email_test likely failed)"

  fail_bad_user:
    runs-on: ubuntu-latest
    name: Fail on bad user account that does not exist
    steps:
      - name: get email after bot
        id: get_email_after_bot_test
        uses: ndelangen/email-by-username-action@main
        continue-on-error: true
        with:
          github-username: "evvvvvaaannnnneeerrrbbb"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Job succeeded (if previous step failed)
        if: ${{ failure() }}
        run: echo "Job succeeded as expected (fail_bad_email_test likely failed)"
